#ifndef __AbstractGPRDRSolver_ADERDG_CLASS_HEADER__
#define __AbstractGPRDRSolver_ADERDG_CLASS_HEADER__

// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================

#include <ostream>
#include <algorithm>

#include "exahype/solvers/ADERDGSolver.h"
#include "kernels/GPRDR_GPRDRSolver_ADERDG/aderdg/Kernels.h"

/**
 * We include Peano's assertion collection here.
 */
#include "tarch/Assertions.h"
#include "tarch/la/Vector.h"

#include "kernels/KernelUtils.h"

namespace GPRDR{
  class GPRDRSolver_ADERDG;
  class AbstractGPRDRSolver_ADERDG;
}

class GPRDR::AbstractGPRDRSolver_ADERDG: public exahype::solvers::ADERDGSolver {
public:
  static constexpr int NumberOfVariables         = GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getNumberOfVariable();
  static constexpr int NumberOfParameters        = GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getNumberOfParameter();
  static constexpr int Order                     = GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBasisSize() -1;
  static constexpr int Dimensions                = GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getDimension();

  static constexpr int NumberOfGlobalObservables = 0;
  static constexpr int NumberOfDMPObservables    = 3; // only of interest if this ADERDGSolver is a component of a LimitingADERDSolver 
  static constexpr int MaxPicardIterations       = Order+1;
  static constexpr bool UseMaxPicardIterations   = false;
  static constexpr double CFL                    = 0.7;
  static constexpr double PNPM                   = 0.33;
  
  // [order][node i]
  static kernels::UnivariateFunction** basisFunction;
  static kernels::UnivariateFunction** basisFunctionFirstDerivative;
  static kernels::UnivariateFunction** basisFunctionSecondDerivative;
  

  // virtual getters for the constexpr's ; TODO(Dominic): Who needs those callbacks?
  int constexpr_getNumberOfVariables()  const { return NumberOfVariables; };
  int constexpr_getNumberOfParameters() const { return NumberOfParameters; };
  int constexpr_getOrder()              const { return Order; };
  double constexpr_getCFLNumber()       const { return CFL; };

  bool isLinear() const override { return false; }
  bool isUseViscousFlux() const override { return false; }

  // Access Objects
  class VariableMetrics;
  class Variables;
  class ReadOnlyVariables;
  class Fluxes;
  class VariableShortcuts;
  class VariableMultiplicities;
  class VariableNames;
  class GlobalObservables;
  class ReadOnlyGlobalObservables;

  AbstractGPRDRSolver_ADERDG(
      const double maximumMeshSize,
      const int maximumMeshDepth,
      const int haloCells,
      const int haloBufferCells,
      const int limiterBufferCells,
      const int regularisedFineGridLevels,
      const exahype::solvers::Solver::TimeStepping timeStepping,
      const int DMPObservables
  );


  /**
   * Default implementation. Please overwrite.
   *
   * See superclass for function's semantics.
   */
  bool isPhysicallyAdmissible(
      const double* const                         solution,
      const double* const                         localDMPObservablesMin,
      const double* const                         localDMPObservablesMax,
      const bool                                  wasTroubledInPreviousTimeStep,
      const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
      const tarch::la::Vector<DIMENSIONS,double>& cellSize,
      const double                                timeStamp) const override { return true; }

  /**
   * Default implementation. Please overwrite.
   *
   * See superclass for function's semantics.
   */
  bool vetoDiscreteMaximumPrincipleDecision(
      const double* const                         solution,
      const double* const                         localDMPObservablesMin,
      const double* const                         localDMPObservablesMax,
      const bool                                  wasTroubledInPreviousTimeStep,
      const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
      const tarch::la::Vector<DIMENSIONS,double>& cellSize,
      const double                                timeStamp) const override { return false; /* do not veto DMP*/ } 

  /**
   * Default implementation. Please overwrite.
   *
   * See superclass for function's semantics.
   */
  void mapDiscreteMaximumPrincipleObservables(double* const observables, const double* const Q) const override {
    if (NumberOfDMPObservables>0) {
      std::copy_n(Q,NumberOfDMPObservables,observables);
    }
  }

  /**
   * Default implementation. Please overwrite.
   *
   * See superclass for function's semantics.
   */
  double getDiscreteMaximumPrincipleRelaxationParameter(
      const double& specifiedRelaxationParameter,
      const int&    observable,
      const double& localMin,
      const double& localMax,
      const double& boundaryMinPerObservable,
      const double& previousMax) const override {
    return specifiedRelaxationParameter;
  }

  /**
   * Default implementation. Please overwrite.
   *
   * See superclass exahype::solvers::Solver for function's semantics.
   */
  int getGeometricLoadBalancingWeight(
      const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
      const tarch::la::Vector<DIMENSIONS,double>& cellSize) override {
    return 1;
  }

  int fusedSpaceTimePredictorVolumeIntegral(double* const lduh,double* const lQhbnd, double* lGradQhbnd, double* const lFhbnd,double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const bool addVolumeIntegralResultToUpdate) override;
  void addUpdateToSolution(double* const luh,const double* const luhOld,const double* const lduh,const double dt) override;
  void surfaceIntegral(double* const lduh,const double* const lFhbnd,const tarch::la::Vector<DIMENSIONS,double>& cellSize); //override; //TODO JMG make override again when enabled back
  void faceIntegral(double* const out,double* const lFhbnd,const int direction, const int orientation,const tarch::la::Vector<DIMENSIONS-1,int>& subfaceIndex,const int levelDelta,const tarch::la::Vector<DIMENSIONS, double>& cellSize,const double dt,const bool addToUpdate) override;    
  void riemannSolver(double* const FL,double* const FR,const double* const QL,const double* const QR,const double t,const double dt, const tarch::la::Vector<DIMENSIONS, double>& cellSize,const int direction, bool isBoundaryFace, int faceIndex) override;
  // old: void boundaryConditions(double* const fluxOut,double* const stateOut,const double* const fluxIn,const double* const stateIn,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const int faceIndex,const int direction) override;
  // old: void boundaryConditions(double* const fluxIn,const double* const stateIn,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const int faceIndex,const int direction) override;
  void boundaryConditions(double* const fluxIn,const double* const stateIn,const double* const gradStateIn, const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt,const int direction,const int orientation) override;
  double stableTimeStepSize(const double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellSize) override;
  void adjustSolution(double* const luh,const tarch::la::Vector<DIMENSIONS,double>& cellCentre,const tarch::la::Vector<DIMENSIONS,double>& cellSize,const double t,const double dt) override; 
  void faceUnknownsProlongation(double* const lQhbndFine,double* const lFhbndFine,const double* const lQhbndCoarse,const double* const lFhbndCoarse,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS-1,int>& subfaceIndex) override;
  //old: void faceUnknownsRestriction(double* const lQhbndCoarse,double* const lFhbndCoarse,const double* const lQhbndFine,const double* const lFhbndFine,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS-1,int>& subfaceIndex) override;
  void volumeUnknownsProlongation(double* const luhFine,const double* const luhCoarse,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS,int>& subcellIndex) override;
  void volumeUnknownsRestriction(double* const luhCoarse,const double* const luhFine,const int coarseGridLevel,const int fineGridLevel,const tarch::la::Vector<DIMENSIONS,int>& subcellIndex) override;
  void resetGlobalObservables(double* const globalObservables) final override;
  void updateGlobalObservables(
      double* const                               globalObservables,
      const double* const                         luh,
      const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
      const tarch::la::Vector<DIMENSIONS,double>& cellSize,
      const double t,
      const double dt) final override;
  void mergeGlobalObservables(double* const globalObservables,const double* const otherObservables) final override;
  void wrapUpGlobalObservables(double* const globalObservables) final override;

  static void constantsToString(std::ostream& os);
  static void abortWithMsg(const char* const msg);

  //padded array size, override default ADERDGSolver values
  int getTempSpaceTimeUnknownsSize()      const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getlQiSize();          }
  int getTempSpaceTimeFluxUnknowns0Size() const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getlFiSize();          }
  int getTempSpaceTimeFluxUnknowns1Size() const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getgradQSize();        }
  int getTempUnknownsSize()               const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getlQhiSize();         }
  int getTempFluxUnknownsSize()           const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getlFhiSize();         }
  int getTempPointForceSourcesSize()      const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getPSiSize();          }
  int getBndFaceSize()                    const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBndFaceSize();      }
  int getBndTotalSize()                   const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBndFaceTotalSize(); }
  int getBndGradQSize()                   const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBndGradQSize();     }
  int getBndFluxSize()                    const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBndFluxSize();      }
  int getBndFluxTotalSize()               const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getBndFluxTotalSize(); }
  int getUpdateSize()                     const {return GPRDR::GPRDRSolver_ADERDG_kernels::aderdg::getUpdateSize(); }

  bool alignTempArray()                  const {return true;}

  bool usePaddedData_nVar() const {return true;}
  bool usePaddedData_nDoF() const {return true;}

  /**
   * @defgroup User PDE kernels
   */
  ///@{
  /**
   * Compute the eigenvalues of the flux tensor per coordinate direction \p d.
   *
   * \param[in] Q  the conserved variables associated with a quadrature node
   *               as C array (already allocated).
   * \param[in] d  the column of the flux vector (d=0,1,...,DIMENSIONS).
   * \param[inout] lambda the eigenvalues as C array (already allocated).
   */
  virtual void eigenvalues(const double* const Q,const int direction,double* const lambda) = 0;

  /**
   * Impose boundary conditions at a point on a boundary face
   * within the time interval [t,t+dt].
   *
   * \param[in]    x         the physical coordinate on the face.
   * \param[in]    t         the start of the time interval.
   * \param[in]    dt        the width of the time interval.
   * \param[in]    faceIndex indexing of the face (0 -- {x[0]=xmin}, 1 -- {x[1]=xmax}, 2 -- {x[1]=ymin}, 3 -- {x[2]=ymax}, and so on,
   *                         where xmin,xmax,ymin,ymax are the bounds of the cell containing point x.
   * \param[in]    d         the coordinate direction the face normal is pointing to.
   * \param[in]    QIn       the conserved variables at point x from inside of the domain
   *                         and time-averaged (over [t,t+dt]) as C array (already allocated).
   * \param[in]    FIn       the normal fluxes at point x from inside of the domain
   *                         and time-averaged (over [t,t+dt]) as C array (already allocated).
   * \param[inout] QOut      the conserved variables at point x from outside of the domain
   *                         and time-averaged (over [t,t+dt]) as C array (already allocated).
   * \param[inout] FOut      the normal fluxes at point x from outside of the domain
   *                         and time-averaged (over [t,t+dt]) as C array (already allocated).
   */
  virtual void boundaryValues(const double* const x,const double t,const double dt,const int faceIndex,const int direction,const double * const fluxIn,const double* const stateIn,const double* const gradStateIn, double *fluxOut,double* stateOut) = 0;

  /**
   * Adjust the conserved variables and parameters (together: Q) at a given time t at the (quadrature) point x.
   *
   * \note Use this function and ::useAdjustSolution to set initial conditions.
   *
   * \param[in]    x         the physical coordinate on the face.
   * \param[in]    t         the start of the time interval.
   * \param[in]    dt        the width of the time interval.
   * \param[inout] Q         the conserved variables (and parameters) associated with a quadrature point
   *                         as C array (already allocated).
   */
  virtual void adjustPointSolution(const double* const x,const double t,const double dt,double* const Q) {}

  /**
   * @TODO LR : document
   */
  virtual void multiplyMaterialParameterMatrix(const double* const Q, double** const rhs);

  /**
   * Compute a pointSource contribution.
   * 
   * @TODO(Leo): Please document
   */
  virtual void pointSource(const double* const Q,const double* const x,const double t,const double dt, double* const forceVector,int n);

  /**
   * Compute the Algebraic Sourceterms.
   * 
   * You may want to overwrite this with your PDE Source (algebraic RHS contributions).
   * However, in all schemes we have so far, the source-type contributions are
   * collected with non-conservative contributions into a fusedSource, see the
   * fusedSource method. From the kernels given with ExaHyPE, only the fusedSource
   * is called and there is a default implementation for the fusedSource calling
   * again seperately the nonConservativeProduct function and the algebraicSource
   * function.
   *
   * \param[in]    x         the physical coordinate
   * \param[in]    t         the start of the time interval.
   * \param[in]    Q the conserved variables (and parameters) associated with a quadrature point
   *                 as C array (already allocated).
   * \param[inout] S the source point as C array (already allocated).
   */
  virtual void algebraicSource(const tarch::la::Vector<DIMENSIONS, double>& x, double t, const double *const Q, double *S);


  /**
   * Compute the nonconservative term $B(Q) \nabla Q$.
   * 
   * This function shall return a vector BgradQ which holds the result
   * of the full term. To do so, it gets the vector Q and the matrix
   * gradQ which holds the derivative of Q in each spatial direction.
   * Currently, the gradQ is a continous storage and users can use the
   * kernels::icellSize2 class in order to compute the positions inside gradQ.
   *
   * @TODO: Check if the following is still right:
   * 
   * !!! Warning: BgradQ is a vector of size NumberOfVariables if you
   * use the ADER-DG kernels for nonlinear PDEs. If you use
   * the kernels for linear PDEs, it is a tensor with dimensions
   * Dim x NumberOfVariables.
   * 
   * \param[in]   Q   the vector of unknowns at the given position
   * \param[in]   gradQ   the gradients of the vector of unknowns,
   *                  stored in a linearized array.
   * \param[inout]  The vector BgradQ (extends nVar), already allocated. 
   *
   */

  virtual void nonConservativeProduct(const double* const Q,const double* const gradQ,double* const BgradQ);

  /**
   * Compute the conserved flux.
   * 
   * \param[in]  Q the conserved variabels (and parameters) associated with a
   *               quadrature point as C array.
   * \param[inout] F a C array with shape [nDim][nVars]. That is, this is an C list
   *               holding pointers to actual lists. Thus, the storage may be noncontinous.
   *               In any case, the storage has already been allocated.
   */
  virtual void flux(const double* const Q,double** const F);

  /**
   * Compute the flux with diffusive component.
   * 
   * \param[in]  Q the conserved variabels (and parameters) associated with a
   *               quadrature point as C array.
   *             gradQ the gradient of the conserved variabels (and parameters) associated
   *                   with a quadrature point as C array.
   * \param[inout] F a C array with shape [nDim][nVars]. That is, this is an C list
   *               holding pointers to actual lists. Thus, the storage may be noncontinous.
   *               In any case, the storage has already been allocated.
   */
  virtual void viscousFlux(const double* const Q, const double* const gradQ, double** const F);
  virtual void viscousEigenvalues(const double* const Q,const int direction,double* const lambda);
  
  /**
   * Resets the vector of global observables to some suitable initial value, e.g.
   * the smallest possible double if one wants to compute the maximum.
   *
   *\param[inout] globalObservables The global observables that we want to reset.
   */
  virtual void resetGlobalObservables(GlobalObservables& globalObservables) const;

  /**
   * Computes observables from a cell's solution values.
   * The result will be merged with the global observables.
   *
   *\param[inout] globalObservables The mapped observables.
   *\param[in]    luh               The solution array.
   *\param[in]    cellSize          The size of a cell.
   */
  virtual void mapGlobalObservables(
      GlobalObservables&                          globalObservables,
      const double* const                         luh,
      const tarch::la::Vector<DIMENSIONS,double>& cellCentre,
      const tarch::la::Vector<DIMENSIONS,double>& cellSize,
      const double t,
      const double dt) const;

  /**
   * This method merges two vectors of (global) observables.
   *
   * For example, if one wants to compute the maximum of global variable i,
   * one should set
   *
   * observables[i] = std::max( globalObservables[i], otherObservables[i])
   *
   * and so on.
   *
   *\param[inout] globalObservables  The (merged) observables.
   *\param[in]    otherObservables   other observables that we want to merge with the first argument.
   */
  virtual void mergeGlobalObservables(
      GlobalObservables&         globalObservables,
      ReadOnlyGlobalObservables& otherObservables) const;

  /**
   * Wrap up the global observables, e.g. finalise an L^2 integral
   * by applying a square root.
   *
   * @note This routine is only called on the global master, after
   * the reduction has completed.
   *
   *\param[inout] observables  The global observables.
   */
  virtual void wrapUpGlobalObservables(GlobalObservables& globalObservables) const;

  
  
  /**
   * Signals a user solver that ExaHyPE just started a new time step.
   *
   * @param[in] minTimeStamp the minimum time stamp (over all cells)
   *
   * @note This function is invoked before the first predictor computation
   * when the non fused time stepping is run. Otherwise, it is invoked after
   * the first predictor computation. It will always be called before
   * "adjustSolution" is invoked.
   *
   * @note [MPI] For convenient reductions consider to specify "global_observables" in
   * the specification file.
   * 
   * @param isFirstTimeStepOfBatchOrNoBatch  if this is the first time step of a batch or no batch is run.
   */
  virtual void beginTimeStep(const double minTimeStamp,const bool isFirstTimeStepOfBatchOrNoBatch) {}

  /**
   * Signals a user solver that ExaHyPE just finished a time step.
   *
   * @param[in] minTimeStamp the minimum time stamp (over all cells)
   *
   * @note This function is invoked after the solution was updated in all
   * cells.
   *
   * @note [MPI] For convenient reductions consider to specify "global_observables" in
   * the specification file. 
   *
   * @param isFirstTimeStepOfBatchOrNoBatch  if this is the first time step of a batch or no batch is run.
   * @param isLastTimeStepOfBatchOrNoBatch   if this is the last time step of a batch or if no batch is run.
   */
  virtual void endTimeStep(const double minTimeStamp,const bool isLastTimeStepOfBatchOrNoBatch)   {}
  ///@}

  //helper function
  inline double* allocateArray(const int size) {return ((double* ) _mm_malloc(sizeof(double)*size, ALIGNMENT));}
  inline void freeArray(double*& array) {_mm_free(array);}

};

#endif // __AbstractGPRDRSolver_ADERDG_CLASS_HEADER__